# IMDB Univaraiate EDS
<span style= "color:cyan"> You have the data for the 100 top-rated movies from the past decade along with various pieces of information about the movie, its actors, and the voters who have rated these movies online. In this assignment, you will try to find some interesting insights into these movies and their voters, using Python. </span>>

In [ ]:
import warnings  # ignoring warnings yall
warnings.filterwarnings('ignore')

In [ ]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("Movie+Assignment+Data.csv")

In [ ]:
df.head()

## Gather InFO

In [ ]:
df.info()

## Check Null

In [ ]:
df.isnull().sum()

In [ ]:
df.duplicated().sum() #check duplicates

## Classification of Numerical and categorical fields ya

In [ ]:
df.columns ## i am having a hard time understanding the columns in the dataset, so I will check them out lol

In [ ]:
df.sample(10) #gathers sample of 10 random rows from the dataset

## Data Analysis 

Now that we have loaded the dataset and inspected it, we see that most of the data is in place. As of now, no data cleaning is required, so let's start with some data manipulation, analysis, and visualisation to get various insights about the data.

### task1 
I see that the numbers in budget and gross are big so lemme just change then into Millions.

In [ ]:
df["Gross"] = df["Gross"] / 1000000 # converting gross to millions for better visualization
df["budget"] = df["budget"] / 1000000 # converting budget to millions for better visualization

In [ ]:
df.tail()

## TAsk 2 
Create a new column called profit which contains the difference of the two columns: gross and budget.
Sort the dataframe using the profit column as reference.
Extract the top ten profiting movies in descending order and store them in a new dataframe - top10.
Plot a scatter or a joint plot between the columns budget and profit and write a few words on what you observed.
Extract the movies with a negative profit and store them in a new dataframe - neg_profit

In [ ]:
df["Profit"]= df["Gross"] - df["budget"] 
df

In [ ]:
top10 = df.sort_values(by = 'Profit', ascending = False).head(10)
print(top10[["Profit"]])

# Scatter plot to check the reln between GRoss & budget

In [ ]:
plt = sns.scatterplot(x= 'budget', y= 'Gross', data = df)

In [ ]:
#find the movies with negative profit

neg_movies= df[df["Profit"] < 0]
neg_movies.head(2)

 ##Can you spot the movie Tangled in the dataset? You may be aware of the movie 'Tangled'. Although its one of the highest grossing movies of all time, it has negative profit as per this result. If you cross check the gross values of this movie (link: https://www.imdb.com/title/tt0398286/), you can see that the gross in the dataset accounts only for the domestic gross and not the worldwide gross. This is true for may other movies also in the list.

#task3: The General Audience and the Critics
You might have noticed the column MetaCritic in this dataset. This is a very popular website where an average score is determined through the scores given by the top-rated critics. Second, you also have another column IMDb_rating which tells you the IMDb rating of a movie. This rating is determined by taking the average of hundred-thousands of ratings from the general audience.

As a part of this subtask, you are required to find out the highest rated movies which have been liked by critics and audiences alike.

Firstly you will notice that the MetaCritic score is on a scale of 100 whereas the IMDb_rating is on a scale of 10. First convert the MetaCritic column to a scale of 10.
Now, to find out the movies which have been liked by both critics and audiences alike and also have a high rating overall, you need to -
Create a new column Avg_rating which will have the average of the MetaCritic and Rating columns
Retain only the movies in which the absolute difference(using abs() function) between the IMDb_rating and Metacritic columns is less than 0.5. Refer to this link to know how abs() funtion works - https://www.geeksforgeeks.org/abs-in-python/ .
Sort these values in a descending order of Avg_rating and retain only the movies with a rating equal to higher than 8 and store these movies in a new dataframe UniversalAcclaim.

In [ ]:
df["MetaCritic"] = df["MetaCritic"] /10 ## my dataset has no imdb raiting column, so I will use the meta critic column to calculate the average rating of the movies.

df["avg_rating"] = df["MetaCritic"]+df["VotesUS"] / 2

In [ ]:
df = df.sort_values( by = "avg_rating", ascending = False)
df

# Find the Most Popular Trios - I
You're a producer looking to make a blockbuster movie. There will primarily be three lead roles in your movie and you wish to cast the most popular actors for it. Now, since you don't want to take a risk, you will cast a trio which has already acted in together in a movie before. The metric that you've chosen to check the popularity is the Facebook likes of each of these actors.
## 
The dataframe has three columns to help you out for the same, viz. actor_1_facebook_likes, actor_2_facebook_likes, and actor_3_facebook_likes. Your objective is to find the trios which has the most number of Facebook likes combined. That is, the sum of actor_1_facebook_likes, actor_2_facebook_likes and actor_3_facebook_likes should be maximum. Find out the top 5 popular trios, and output their names in a list.

In [ ]:
total_actor_likes = df["actor_1_facebook_likes"] + df["actor_2_facebook_likes"] + df["actor_3_facebook_likes"]
df["total_actor_likes"] = total_actor_likes

df = df.sort_values( by = "total_actor_likes", ascending = False)
df.head(5)

In [ ]:
df.columns

## Subtask 2.6: Runtime Analysis
<span style = "color : cyan" >
There is a column named Runtime in the dataframe which primarily shows the length of the movie. It might be intersting to see how this variable this distributed. Plot a histogram or distplot of seaborn to find the Runtime range most of the movies fall into.</span>

In [ ]:
plt = sns.histplot(df["Runtime"], bins = 20)

# R-Rated Movies
Although R rated movies are restricted movies for the under 18 age group, still there are vote counts from that age group. Among all the R rated movies that have been voted by the under-18 age group, find the top 10 movies that have the highest number of votes i.e.CVotesU18 from the movies dataframe. Store these in a dataframe named PopularR.

In [ ]:
PopularR = df[df["content_rating"] == "R"]
PopularR = PopularR.sort_values(by = "CVotesU18", ascending = False)[["Title", "CVotesU18", "content_rating"]]
PopularR.head(10)

#  Demographic analysis
If you take a look at the last columns in the dataframe, most of these are related to demographics of the voters (in the last subtask, i.e., 2.8, you made use one of these columns - CVotesU18). We also have three genre columns indicating the genres of a particular movie. We will extensively use these columns for the third and the final stage of our assignment wherein we will analyse the voters across all demographics and also see how these vary across various genres. So without further ado, let's get started with demographic analysis.

## Subtask 3.1 Combine the Dataframe by Genres
There are 3 columns in the dataframe - genre_1, genre_2, and genre_3. As a part of this subtask, you need to aggregate a few values over these 3 columns.

### 

 First create a new dataframe df_by_genre that contains genre_1, genre_2, and genre_3 and all the columns related to CVotes/Votes from the movies data frame. There are 47 columns to be extracted in total.  

Now, Add a column called cnt to the dataframe df_by_genre and initialize it to one. You will realise the use of this column by the end of this subtask.
First group the dataframe df_by_genre by genre_1 and find the sum of all the numeric columns such as cnt, columns related to CVotes and Votes columns and store it in a dataframe df_by_g1.
Perform the same operation for genre_2 and genre_3 and store it dataframes df_by_g2 and df_by_g3 respectively.
Now that you have 3 dataframes performed by grouping over genre_1, genre_2, and genre_3 separately, it's time to combine them. For this, add the three dataframes and store it in a new dataframe df_add, so that the corresponding values of Votes/CVotes get added for each genre.There is a function called add() in pandas which lets you do this. You can refer to this link to see how this function works. https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DataFrame.add.html
The column cnt on aggregation has basically kept the track of the number of occurences of each genre.Subset the genres that have atleast 10 movies into a new dataframe genre_top10 based on the cnt column value.
Now, take the mean of all the numeric columns by dividing them with the column value cnt and store it back to the same dataframe. We will be using this dataframe for further analysis in this task unless it is explicitly mentioned to use the dataframe movies.
Since the number of votes can't be a fraction, type cast all the CVotes related columns to integers. Also, round off all the Votes related columns upto two digits after the decimal point.

In [ ]:
df.columns

In [ ]:
df_by_genre=df.loc[:,"CVotes10":"VotesnUS"]
df_by_genre[["genre_1","genre_2","genre_3"]]=df[["genre_1","genre_2","genre_3"]]
df_by_genre

In [ ]:
df_by_genre["cnt"]=1

In [ ]:
df_by_genre[["genre_1","genre_2","genre_3"]]

In [ ]:
df_by_g1 = df_by_genre.groupby("genre_1").sum(numeric_only=True)
df_by_g2 = df_by_genre.groupby("genre_2").sum(numeric_only=True)
df_by_g3 = df_by_genre.groupby("genre_3").sum(numeric_only=True)

,CVotes10,CVotes09,CVotes08,CVotes07,CVotes06,CVotes05,CVotes04,CVotes03,CVotes02,CVotes01,...,Votes45A,Votes45AM,Votes45AF,Votes1000,VotesUS,VotesnUS,genre_1,genre_2,genre_3,cnt
2,23325,29830,40564,20296,5842,1669,558,309,182,493,...,8.0,7.9,8.4,7.1,8.1,8.0,Biography,Drama,NaN,1
27,584839,485218,304457,130972,46393,20595,10050,6631,5243,15365,...,8.1,8.1,8.0,8.2,8.7,8.8,Action,Adventure,Sci-Fi,1
14,91765,127521,183578,104658,33027,10059,3710,1903,1225,3301,...,7.7,7.7,7.9,7.4,8.1,7.9,Action,Adventure,Sci-Fi,1
4,18191,33532,46596,29626,11879,4539,1976,1233,888,1834,...,7.6,7.6,7.6,7.1,7.9,7.8,Drama,NaN,NaN,1
8,380589,341965,281426,134959,50406,20106,9589,5713,4073,11988,...,7.9,7.9,7.9,7.8,8.4,8.4,Action,Thriller,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,155391,161810,166378,99402,40734,18060,8751,5970,4489,15768,...,7.9,7.8,8.2,7.7,8.2,7.9,Action,Adventure,Fantasy,1
34,89986,127616,169693,122275,57564,25393,12286,7868,5751,12473,...,7.7,7.7,7.5,7.5,7.9,7.8,Drama,Sci-Fi,Thriller,1
0,74245,71191,64640,38831,17377,8044,3998,2839,2407,6802,...,7.6,7.6,7.5,7.1,8.3,8.1,Comedy,Drama,Music,1
3,55533,87850,109536,65440,26913,10556,5057,3083,2194,4734,...,7.6,7.6,7.7,7.3,8.0,7.9,Drama,Mystery,Sci-Fi,1
6,38952,51465,102744,83322,32430,10744,3786,1854,1038,2667,...,7.5,7.4,7.8,7.1,7.6,7.4,Action,Adventure,Fantasy,1

In [218]:
df_by_g1

,CVotes10,CVotes09,CVotes08,CVotes07,CVotes06,CVotes05,CVotes04,CVotes03,CVotes02,CVotes01,...,Votes3044F,Votes45A,Votes45AM,Votes45AF,Votes1000,VotesUS,VotesnUS,genre_2,genre_3,cnt
genre_1,,,,,,,,,,,,,,,,,,,,,
Action,2928407,3261919,4247693,2662020,986774,364234,156150,89483,61975,162426,...,210.0,206.5,206.0,209.0,197.2,215.8,209.5,AdventureAdventureThrillerSci-FiAdventureAdven...,Sci-FiSci-FiSci-FiMysterySci-FiSci-FiDramaSci-...,27
Adventure,1058779,1179818,1560541,966275,365486,136985,58559,33174,22018,48100,...,93.5,92.0,91.6,93.8,88.9,95.3,93.5,DramaDramaDramaComedyDramaComedyDramaFamilyBio...,ThrillerFamilySci-FiDramaWesternDramaSci-FiFan...,12
Animation,681562,798227,1153214,722782,251076,83069,30718,15733,10026,25193,...,87.8,84.5,84.1,86.7,80.0,87.6,86.1,AdventureAdventureActionActionActionAdventureA...,ComedyDramaAdventureAdventureAdventureComedyCo...,11
Biography,666831,1088430,1654704,962977,306247,100005,38874,21536,15365,37469,...,101.3,100.5,100.0,102.9,94.7,103.3,101.5,DramaComedyDramaComedyDramaDramaDramaDramaDram...,DramaSportCrimeThrillerThrillerRomanceHistoryH...,13
Comedy,371217,496905,770395,518566,205434,81933,35788,20965,15286,33241,...,68.9,67.7,67.5,68.7,62.7,70.9,69.4,DramaDramaDramaDramaDramaHorrorDramaFantasyDrama,RomanceRomanceRomanceRomanceFantasyRomanceMusic,9
Crime,383290,690221,1083469,627593,206756,71460,30336,17190,11757,25839,...,68.8,68.7,68.6,69.6,66.3,71.9,70.1,DramaDramaDramaDramaDramaDramaDramaDramaDrama,ThrillerMysteryThrillerMysteryThrillerThriller...,9
Drama,1080725,1494053,1827363,1078966,417205,163874,75525,45846,32068,71464,...,139.7,137.7,137.2,138.7,130.0,143.2,141.1,MusicalWesternThrillerMusicRomanceHistorySport...,RomanceSci-FiThrillerSci-FiThrillerSci-Fi,18
Mystery,150405,230844,278844,132349,45167,15615,7061,3780,2662,4703,...,8.0,7.5,7.4,7.6,7.6,7.8,8.1,Thriller,,1

In [219]:
df_by_g2

,CVotes10,CVotes09,CVotes08,CVotes07,CVotes06,CVotes05,CVotes04,CVotes03,CVotes02,CVotes01,...,Votes3044F,Votes45A,Votes45AM,Votes45AF,Votes1000,VotesUS,VotesnUS,genre_1,genre_3,cnt
genre_2,,,,,,,,,,,,,,,,,,,,,
Action,238060,285510,430062,260106,88580,29250,10820,5521,3598,8821,...,31.8,30.5,30.4,31.4,29.0,31.8,31.1,AnimationAnimationAnimationAnimation,AdventureAdventureAdventureAdventure,4
Adventure,2297820,2548864,3271725,2055600,758009,272735,113691,64623,44121,116937,...,173.9,169.2,168.4,172.8,162.7,176.4,171.6,ActionActionAnimationActionActionActionActionA...,Sci-FiSci-FiComedySci-FiMysterySci-FiSci-FiSci...,22
Biography,185172,313178,576374,370003,119348,38643,14844,7974,5248,13828,...,38.5,38.0,37.9,38.8,35.4,39.4,38.4,ActionActionAdventureActionAction,DramaDramaDramaDramaDrama,5
Comedy,428995,624720,854162,512668,193916,76752,35193,20995,14798,30509,...,53.4,53.0,53.1,53.1,51.0,55.5,54.3,BiographyBiographyAdventureAdventureActionAdve...,DramaCrimeDramaDramaRomanceDrama,7
Crime,19576,40247,85359,64633,24920,8548,3261,1669,970,1689,...,7.2,7.6,7.6,7.4,7.2,7.8,7.6,Action,Drama,1
Drama,1923492,2761237,4112363,2492241,853434,300100,124511,70205,49642,112896,...,270.1,267.9,267.1,271.8,253.4,278.2,272.6,BiographyComedyAdventureBiographyCrimeComedyCr...,RomanceThrillerSportThrillerRomanceMysteryFami...,35
Family,68937,54947,102488,80465,31205,11792,4808,2454,1617,4522,...,8.1,7.4,7.3,8.0,6.7,7.9,7.5,Adventure,Fantasy,1
Fantasy,270616,290831,447307,291071,120920,47215,19848,10871,6885,14702,...,23.3,23.0,22.8,23.7,22.1,23.4,23.2,AdventureAdventureComedy,Romance,3
History,15757,32840,83322,63800,19183,5178,1657,735,419,878,...,7.5,7.7,7.6,7.9,7.4,7.7,7.5,Drama,Thriller,1
Horror,16572,19818,44460,35863,13456,4588,1684,855,479,848,...,7.7,7.5,7.4,7.7,7.1,7.7,7.5,Comedy,,1
Music,110404,161864,132656,56007,16577,6031,2937,1859,1263,2723,...,8.2,8.1,8.1,8.2,8.0,8.6,8.4,Drama,,1
Musical,54268,47750,63323,45160,22393,10744,5551,3484,2490,5020,...,7.6,7.4,7.3,7.7,6.6,7.6,7.5,Drama,Romance,1
Mystery,85313,152619,233474,148176,55575,20135,8863,5034,3359,6916,...,15.2,15.2,15.2,15.1,14.8,15.9,15.6,DramaDrama,Sci-FiSci-Fi,2
Romance,230425,270702,353326,215355,87701,35226,16298,9448,6708,14889,...,38.7,37.9,37.8,37.7,35.3,39.7,39.2,DramaDramaDramaDramaDrama,Sci-Fi,5
Sci-Fi,350243,361819,433983,284879,125143,53350,24462,15069,10747,28001,...,15.6,15.6,15.6,15.6,14.9,16.2,15.7,ActionDrama,Thriller,2
Sport,21364,28964,58237,45563,16432,5118,1655,848,464,1151,...,7.4,7.3,7.3,7.5,7.1,7.9,7.5,Drama,,1
Thriller,624792,709424,734770,365134,135892,52714,25734,15558,10716,25417,...,24.2,22.9,22.8,22.9,23.0,24.2,24.5,ActionDramaMystery,,3
War,15911,17607,32570,24461,10274,3848,1387,726,342,755,...,7.7,7.6,7.5,8.0,6.6,7.6,7.5,Drama,,1
Western,234824,339329,286911,121445,38251,14227,6469,4149,3181,8065,...,8.3,8.0,8.0,8.1,7.8,8.4,8.4,Drama,,1

In [220]:

df_by_g3

,CVotes10,CVotes09,CVotes08,CVotes07,CVotes06,CVotes05,CVotes04,CVotes03,CVotes02,CVotes01,...,Votes3044F,Votes45A,Votes45AM,Votes45AF,Votes1000,VotesUS,VotesnUS,genre_1,genre_2,cnt
genre_3,,,,,,,,,,,,,,,,,,,,,
Adventure,238060,285510,430062,260106,88580,29250,10820,5521,3598,8821,...,31.8,30.5,30.4,31.4,29.0,31.8,31.1,AnimationAnimationAnimationAnimation,ActionActionActionAction,4
Comedy,583404,653362,882294,559835,200937,68167,26488,14258,9307,24617,...,56.0,54.3,54.1,55.3,51.7,56.2,55.2,AnimationActionAnimationAnimationAnimationAnim...,AdventureAdventureAdventureAdventureAdventureA...,7
Crime,171660,236650,250667,129164,46715,18682,8674,5854,4258,9689,...,7.7,7.6,7.6,7.5,7.8,8.1,8.1,Biography,Comedy,1
Drama,400221,680085,1167327,748493,258717,88338,35439,19075,12475,26948,...,92.0,91.2,91.0,92.7,86.1,94.5,92.3,BiographyActionAnimationAdventureActionAdventu...,ComedyBiographyAdventureComedyBiographyComedyA...,12
Family,29228,40728,77893,62936,27932,11179,4664,2674,1700,3023,...,7.4,7.5,7.5,7.6,7.4,7.7,7.5,Adventure,Drama,1
Fantasy,301836,311392,442460,308676,120911,46269,19555,11362,7808,24139,...,31.7,30.4,30.0,31.8,28.4,31.5,30.5,AdventureComedyActionAction,FamilyDramaAdventureAdventure,4
History,135504,227547,311209,159262,48678,16055,6307,3649,2729,8413,...,23.8,23.3,23.1,24.2,22.0,24.5,23.7,BiographyBiographyCrime,DramaDramaDrama,3
Music,74245,71191,64640,38831,17377,8044,3998,2839,2407,6802,...,7.8,7.6,7.6,7.5,7.1,8.3,8.1,Comedy,Drama,1
Mystery,274446,443661,654167,375087,128131,44818,18755,10578,7149,17825,...,31.5,30.4,30.3,31.3,29.3,31.9,31.3,ActionCrimeCrimeCrime,AdventureDramaDramaDrama,4
Romance,319534,418790,715954,497486,193588,75675,32615,18250,12492,25186,...,60.9,59.9,59.7,61.2,54.6,62.1,60.9,ComedyDramaComedyBiographyActionComedyComedyCo...,DramaMusicalDramaDramaComedyDramaDramaFantasy,8
Sci-Fi,1975041,2169036,2569011,1517219,546668,200825,87463,50835,35424,86434,...,117.6,115.5,115.2,115.9,113.0,121.3,118.3,ActionActionActionActionActionActionActionAdve...,AdventureAdventureAdventureAdventureAdventureA...,15
Sport,95717,140282,214806,138600,44470,13821,5155,2509,1828,4083,...,15.2,15.2,15.2,15.0,14.2,16.0,15.6,BiographyAction,DramaDrama,2
Thriller,456909,756067,1258608,810665,280154,97239,39547,22382,15051,32213,...,75.9,76.7,76.5,77.8,73.2,78.9,77.0,AdventureCrimeCrimeBiographyDramaBiographyCrim...,DramaDramaDramaDramaHistoryDramaDramaDramaAdve...,10
War,36753,54703,111271,82505,30231,10553,4303,2388,1629,3246,...,7.4,7.4,7.4,7.4,6.8,7.6,7.5,Action,Drama,1
Western,21094,40901,91825,67175,23055,7191,2678,1305,779,1672,...,7.5,7.7,7.7,7.7,7.3,7.9,7.6,Adventure,Drama,1

In [221]:
# Add the grouped data frames and store it in a new data frame
df_add=df_by_g1.add(df_by_g2,fill_value=0)
df_add=df_add.add(df_by_g3,fill_value=0)
df_add

TypeError: Invalid value '0' for dtype 'str'. Value should be a string or missing value, got 'int' instead.